// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIaPMAl4wA8-KgkEl6_DfCvQox3HdKOho',
    appId: '1:548757726267:web:ee907e33457c4bb67a681e',
    messagingSenderId: '548757726267',
    projectId: 'fitathome-flutter',
    authDomain: 'fitathome-flutter.firebaseapp.com',
    storageBucket: 'fitathome-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXgasZSsa7eYbKC3nQMgXyRCE_R08rsQk',
    appId: '1:548757726267:android:568a4f2dc54106d77a681e',
    messagingSenderId: '548757726267',
    projectId: 'fitathome-flutter',
    storageBucket: 'fitathome-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfMH8314i_Z9eSmjEINxJKMU3nDkC44LM',
    appId: '1:548757726267:ios:5b7b750ed064b1857a681e',
    messagingSenderId: '548757726267',
    projectId: 'fitathome-flutter',
    storageBucket: 'fitathome-flutter.appspot.com',
    iosClientId: '548757726267-8fht4mjel12b9cmt80hvrtbucomo572s.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitathome',
  );
}
